"""
Centralized prompt templates. Keeping these in one module (rather than
scattered as string literals inside each service module) is what the
spec asks for, and it also makes it much easier to audit/tune what every
step is actually asking the LLM to do without hunting through service logic.
"""
from __future__ import annotations

SYSTEM_ANALYSIS_PROMPT = """\
You are performing System Analysis in a security threat-modeling platform.
Given raw system input (an OpenAPI spec, a free-text architecture
description, or manual entries), extract a structured system model.

Return STRICT JSON with exactly this shape:
{
  "assets": [{"name": str, "asset_type": str, "technology": str, "criticality": "Critical|High|Medium|Low"}],
  "users": [{"name": str, "role": str}],
  "services": [{"name": str, "technology": str}],
  "databases": [{"name": str, "technology": str}],
  "external_entities": [{"name": str, "description": str}],
  "trust_boundaries": [{"name": str, "description": str}],
  "data_flows": [{"source": str, "destination": str, "description": str, "protocol": str, "data_classification": str}],
  "authentication": [{"mechanism": str, "applies_to": str}]
}
asset_type must be one of: User, Admin, Web Application, API, Authentication Service,
Database, Payment Service, External API, Cloud Service, Monitoring Service, Storage.
Only use information present or reasonably inferable from the input. Do not invent
components that have no basis in the input.
"""

DIAGRAM_ANALYSIS_PROMPT = """\
You are performing System Analysis by analyzing an architecture diagram image for
a security threat-modeling platform. Identify every component, service,
database, external entity, user/actor, trust boundary, and data flow (arrow)
visible in the diagram. Infer HTTP/protocol labels only if actually shown or
strongly implied (e.g. an arrow explicitly labeled "HTTPS"); otherwise use
"unspecified" rather than guessing.

Return STRICT JSON with exactly this shape:
{
  "assets": [{"name": str, "asset_type": str, "technology": str, "criticality": "Critical|High|Medium|Low"}],
  "users": [{"name": str, "role": str}],
  "services": [{"name": str, "technology": str}],
  "databases": [{"name": str, "technology": str}],
  "external_entities": [{"name": str, "description": str}],
  "trust_boundaries": [{"name": str, "description": str}],
  "data_flows": [{"source": str, "destination": str, "description": str, "protocol": str, "data_classification": str}],
  "authentication": [{"mechanism": str, "applies_to": str}]
}
asset_type must be one of: User, Admin, Web Application, API, Authentication Service,
Database, Payment Service, External API, Cloud Service, Monitoring Service, Storage.
Base every field strictly on what is visible in the image. If a trust boundary is
drawn (e.g. a dashed box or "DMZ" label), capture it. If nothing in the image
supports a field, omit that entry rather than inventing one.
"""

THREAT_MODELING_REFINEMENT_PROMPT = """\
You are performing Threat Modeling. You are given one asset from a system
under review, and a list of CANDIDATE threats generated by a deterministic
STRIDE rule library, plus RETRIEVED_CONTEXT from a security knowledge base.

For each candidate threat, decide whether it genuinely applies given the
asset's specific technology/criticality/trust zone, and refine its
description to be concrete to this system rather than generic. You may also
propose at most one ADDITIONAL threat if the retrieved context clearly
supports it and it is not already covered.

You MUST NOT invent an OWASP/CWE/MITRE ATT&CK identifier that does not
appear in RETRIEVED_CONTEXT. If nothing in RETRIEVED_CONTEXT supports a
mapping for a given threat, leave owasp_category/cwe_id/mitre_attack_technique
as null for that threat.

Return STRICT JSON:
{
  "threats": [
    {
      "title": str,
      "description": str,
      "stride_category": "Spoofing|Tampering|Repudiation|Information Disclosure|Denial of Service|Elevation of Privilege",
      "likelihood": "High|Medium|Low",
      "impact": "High|Medium|Low",
      "confidence": number between 0 and 1,
      "recommended_mitigation": str,
      "owasp_category": str or null,
      "cwe_id": str or null,
      "mitre_attack_technique": str or null,
      "reasoning_summary": str
    }
  ]
}
"""

ATTACK_SCENARIO_PROMPT = """\
You are generating an attack scenario for an AUTHORIZED, controlled security
testing platform. Given a threat, produce ONE structured attack scenario
suitable for execution only in an authorized test/lab environment. Never
include instructions for attacking systems the user has not authorized;
this scenario is scoped to the test environment the platform already
enforces via an allowlist.

Return STRICT JSON:
{
  "attacker_profile": str,
  "target": str,
  "objective": str,
  "precondition": str,
  "scenario_narrative": str,
  "expected_secure_behavior": str
}
"""

SECURITY_TEST_GENERATION_PROMPT = """\
You are generating a security test for an AUTHORIZED, controlled
security-testing platform. Convert the given threat + attack scenario into
ONE concrete, executable security test that a Controlled Test Execution
engine can run safely against an authorized lab/staging target (never a
real production or third-party system).

Only propose SAFE test categories: authorization checks, authentication
checks, input validation checks, API configuration/header checks, or
workflow/state checks. Never propose destructive actions (data deletion,
resource exhaustion beyond a bounded number of requests, or anything
requiring exploit payloads that could damage the target).

Return STRICT JSON:
{
  "objective": str,
  "preconditions": str,
  "endpoint": str,
  "http_method": "GET|POST|PUT|PATCH|DELETE",
  "required_role": str,
  "test_steps": [str, ...],
  "expected_result": str,
  "validation_criteria": str,
  "risk_level": "Critical|High|Medium|Low|Informational"
}
"""
